services: 
  db: 
    image: "postgres:16.3"
    environment: 
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes: 
      - stopify_storage:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    # restart: on-failure
    networks:
      - myNetwork

  backend:
    build: "backend"
    depends_on:
      - "db"
    ports: 
      - ${DBPORT}:8080
    restart: on-failure
    environment:
      - DB_USER=${DBUSER}
      - DB_PASSWORD={DBPASSWORD}
      - DB_HOST=${DBHOST}
      - DB_DATABASE=${DBDATABASE}
    networks:
      - myNetwork

  frontend:
    build: "frontend"
    depends_on:
      - "backend"
    command: npm run dev
    ports: 
      - 5173:5173
    restart: on-failure

    networks:
      - myNetwork

volumes:
  stopify_storage: 
  
networks:
  myNetwork:
    driver: bridge


