services:
  db:
    image: "postgres:16.3"
    container_name: db
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - stopify_storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - myNetwork

  backend:
    build: "backend"
    container_name: backend
    depends_on:
      - "db"
    ports:
      - 8080:8080
    environment:
      - DB_USER=${PGUSER}
      - DB_PASSWORD=${PGPASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${PGDATABASE}
      - PORT=8080
    networks:
      - myNetwork
    restart: on-failure

  frontend:
    build: "frontend"
    container_name: frontend
    depends_on:
      - "backend"
    ports:
      - 5173:5173
    networks:
      - myNetwork


volumes:
  stopify_storage:

networks:
  myNetwork:
    driver: bridge


