version: "16"

services: 
  db: 
    image: "postgres:16.3"
    environment: 
      - POSTGRES_USER: "${PGUSER}"
      - POSTGRES_PASSWORD: "${PGPASSWORD}"
      - POSTGRES_DB: "${PGDATABASE}"
    volumes: 
      - stopify_storage:/var/lib/postgresql/data
    ports: 5432:5432
  
  backend:
    build: "backend"
    depends_on:
      - "db"
    ports: 
      - "${DBPORT}:8080"

  frontend:
    build: "frontend"
    depends_on:
      - "backend"
    command: npm run dev
    ports: 
      - 5173:5173

volumes:
  stopify_storage: 
  



